todoproject/todoapp/urls.py
from . import views
from django.urls import path


app_name='todoapp'
urlpatterns = [
    path('', views.task, name='task'),
    path('delete/<int:taskid>/',views.delete,name='delete'),
    path('update/<int:id>/',views.update,name='update'),
    path('cbvhome/',views.TasklistView.as_view(),name='cbvhome'),
    path('cbvdetail/<int:pk>/',views.detailviewlist.as_view(),name='cbvdetail'),
    path('cbvupdate/<int:pk>/',views.taskupdateview.as_view(),name='cbvupdate'),
    path('cbvdelete/<int:pk>/', views.taskdeleteview.as_view(),name='cbvdelete')

]

todoproject/todoproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todoapp.urls'))
]

if settings.DEBUG:
    urlpatterns += static (settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static (settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

todoproject/todoapp/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    name = models.CharField(max_length=250)
    priority = models.IntegerField()
    date = models.DateField()
    def __str__(self):
        return self.name

todoproject/todoapp/forms.py
from . models import Task
from django import forms

class Todoform (forms.ModelForm):
    class Meta:
        model=Task
        fields=['name','priority','date']

todoproject/todoapp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from . models import Task
from . forms import Todoform
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView,DeleteView

class detailviewlist(DetailView):
    model=Task
    template_name="detail.html"
    context_object_name='t'

class TasklistView(ListView):
    model=Task
    template_name="home.html"
    context_object_name='ta'

class taskupdateview(UpdateView):
    model=Task
    template_name="update.html"
    context_object_name='tas'
    fields=('name','priority','date')
    def get_success_url(self):
        return reverse_lazy('cbvdetail',kwargs={'pk':self.object.id})

class taskdeleteview(DeleteView):
    model=Task
    template_name="delete.html"
    context_object_name='t'



# Create your views here.
def task(request):
    taask=Task.objects.all()
    if request.method=='POST':
        name=request.POST.get('task','')
        priority = request.POST.get('priority', '')
        date = request.POST.get('date','')
        tas=Task(name=name,priority=priority,date=date)
        tas.save()
    return render(request,"home.html",{'ta':taask})
def delete(request,taskid):
    ta=Task.objects.all()
    if request.method =='POST':
        ta.delete()
        return redirect('/')
    return render(request,"delete.html")

def update(request,id):
    tas=Task.objects.get(id=id)
    f=Todoform(request. POST or None, instance=tas)
    if f.is_valid():
        f.save()
        return redirect ('/')
    return render(request,"edit.html",{'f':f,'task':tas})

todoproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"  integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">

</head>
<body>
{% block content %}
{% endblock %}

</body>
</html>

todoproject/templates/delete.html
{% extends 'base.html' %}

{% block content %}
<form method="POST" style="background-color:plum;">
    {% csrf_token %}
    <p>Did you finsh the task?</p>
    <button>YES</button>


</form>

{% endblock %}

todoproject/templates/detail.html
{% extends 'base.html' %}

{% block content %}

 <div class="shadow card" >
                <div class="card-body" >
                    <h4> {{t.name}} - {{t.priority}} </h4>
                    <p><h5> {{t.date}} </h5></p>
                    <a class="btn btn-danger" href="{% url 'todoapp:delete' t.id  %}"> Done </a>
                    <a class="btn btn-success" href="{% url 'todoapp:update' t.id  %}"> Edit </a>

                </div>
            </div>
{% endblock %}

todoproject/templates/edit.html
{% extends 'base.html' %}

{% block content %}
<form method="POST" style="background-color:plum;">
    {% csrf_token %}
    {{ f.as_p }}
    <button type="submit" >Confirm </button>


</form>

{% endblock %}

todoproject/templates/home.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid" style="background-color:aquamarine;">
    <div class="row" >
        <div class="col-md-12" >
            <div class="banner">
                <div class="banner-text">
                    <h1> To Do List</h1>
                </div>

            </div>

        </div>
    </div>
</div>

<div class="container" style="background-color:aquamarine;" >
    <div class="row" >
        <div class="col-md-6" style="background-color:aquamarine;">
        <form method="POST" class="p-3 shadow" style="background-color:paleturquoise";>
        {% csrf_token %}
            <div class="form-group" >
     <input type="text" class="form-control" name="task" placeholder="Task name">
</div>
<div class="form-group">
     <input type="text" class="form-control" name="priority" placeholder="Enter your priority">
</div>
            <div class="form-group">
                <input type="date" class="form-control" name="date" placeholder="Enter your date">
            </div>
        <input type="submit" class="btn btn-success ">

        </form>




    </div>
        <div class="col-md-6">
            <h3>Tasks to do </h3>
            {% for i in ta %}
            <div class="shadow card" >
                <div class="card-body" >
                    <h4> {{i.name}} - {{i.priority}} </h4>
                    <p><h5> {{i.date}} </h5></p>
                    <a class="btn btn-danger" href="{% url 'todoapp:delete' i.id  %}"> Done </a>
                    <a class="btn btn-success" href="{% url 'todoapp:update' i.id  %}"> Edit </a>

                </div>
            </div>
            <br>
             {% endfor %}

        </div>
</div>
</div>


{% endblock %}

todoproject/templates/update.html
{% extends 'base.html' %}
{% block content %}
<div class="card">
    <div class="card-header">
        <div class="card-title">
           <h2 style="background-color:thistle"> Update Task </h2>
        </div>
        <div class="card-body">
            <form method="POST" style="background-color:plum;">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" >Confirm </button>
           </form>
        </div>
    </div>

</div>

{% endblock %}